CREATE TABLE ADM_SLATE_NL_GUIDS
( SLATE_REFID       VARCHAR2(9 CHAR),
  BANNER_REFID      VARCHAR2(9 CHAR),
  BANNER_REFID_DATE DATE,
  BANNER_PIDM       NUMBER(8),
  BANNER_ID         VARCHAR2(9 CHAR),
  FULL_NAME         VARCHAR2(200 CHAR),
  TERM_CODE         VARCHAR2(6 CHAR),
  MATCH_STATUS      VARCHAR2(1 CHAR),
  ACTIVITY_DATE     DATE,
  USER_ID           VARCHAR2(30 CHAR),
  ORIGIN_FILE       VARCHAR2(30 CHAR)
);
COMMIT;
COMMENT ON TABLE ADM_SLATE_NL_GUIDS IS 'Table to log Non-loaded GORADID_ADDITIONAL_ID from Slate';
